// Auto-generated seed data — 100 tools, 16 users
export const INITIAL_USERS = [
  {
    "id": "admin1",
    "name": "System Admin",
    "location": "Colombo",
    "phone": "0112345678",
    "rating": 5,
    "reviewCount": 100,
    "avatar": "AD",
    "isVerified": true,
    "nic": "198012345678",
    "password": "admin",
    "email": "admin@renttool.lk",
    "role": "admin"
  },
  {
    "id": "u1",
    "name": "Kasun Perera",
    "location": "Colombo 05",
    "phone": "0771234567",
    "rating": 4.9,
    "reviewCount": 12,
    "avatar": "KP",
    "isVerified": true,
    "nic": "199512345678",
    "password": "kasun123",
    "email": "kasun@email.com",
    "role": "user"
  },
  {
    "id": "u2",
    "name": "Nimal Silva",
    "location": "Kandy",
    "phone": "0719876543",
    "rating": 4.7,
    "reviewCount": 5,
    "avatar": "NS",
    "isVerified": false,
    "nic": "",
    "password": "nimal123",
    "email": "nimal@email.com"
  },
  {
    "id": "u3",
    "name": "Dilini Fernando",
    "location": "Maharagama",
    "phone": "0765554433",
    "rating": 5,
    "reviewCount": 8,
    "avatar": "DF",
    "isVerified": true,
    "nic": "199298765432",
    "password": "dilini123",
    "email": "dilini@email.com"
  },
  {
    "id": "u4",
    "name": "Ruwan Bandara",
    "location": "Gampaha",
    "phone": "0772345678",
    "rating": 4.6,
    "reviewCount": 7,
    "avatar": "RB",
    "isVerified": true,
    "nic": "198845678901",
    "password": "ruwan123",
    "email": "ruwan@email.com"
  },
  {
    "id": "u5",
    "name": "Chamara Jayasinghe",
    "location": "Galle",
    "phone": "0713456789",
    "rating": 4.8,
    "reviewCount": 10,
    "avatar": "CJ",
    "isVerified": true,
    "nic": "199123456789",
    "password": "chamara123",
    "email": "chamara@email.com"
  },
  {
    "id": "u6",
    "name": "Pradeep Weerasinghe",
    "location": "Matara",
    "phone": "0764567890",
    "rating": 4.5,
    "reviewCount": 6,
    "avatar": "PW",
    "isVerified": false,
    "nic": "",
    "password": "pradeep123",
    "email": "pradeep@email.com"
  },
  {
    "id": "u7",
    "name": "Sanjeewa Kumara",
    "location": "Kurunegala",
    "phone": "0775678901",
    "rating": 4.7,
    "reviewCount": 9,
    "avatar": "SK",
    "isVerified": true,
    "nic": "197867890123",
    "password": "sanjeewa123",
    "email": "sanjeewa@email.com"
  },
  {
    "id": "u8",
    "name": "Malini Ratnayake",
    "location": "Negombo",
    "phone": "0716789012",
    "rating": 4.9,
    "reviewCount": 11,
    "avatar": "MR",
    "isVerified": true,
    "nic": "199534567890",
    "password": "malini123",
    "email": "malini@email.com"
  },
  {
    "id": "u9",
    "name": "Thilak Dissanayake",
    "location": "Anuradhapura",
    "phone": "0767890123",
    "rating": 4.4,
    "reviewCount": 4,
    "avatar": "TD",
    "isVerified": false,
    "nic": "",
    "password": "thilak123",
    "email": "thilak@email.com"
  },
  {
    "id": "u10",
    "name": "Sumudu Liyanage",
    "location": "Ratnapura",
    "phone": "0778901234",
    "rating": 4.8,
    "reviewCount": 13,
    "avatar": "SL",
    "isVerified": true,
    "nic": "199012345678",
    "password": "sumudu123",
    "email": "sumudu@email.com"
  },
  {
    "id": "u11",
    "name": "Buddhika Samaraweera",
    "location": "Badulla",
    "phone": "0719012345",
    "rating": 4.6,
    "reviewCount": 3,
    "avatar": "BS",
    "isVerified": true,
    "nic": "198956789012",
    "password": "buddhika123",
    "email": "buddhika@email.com"
  },
  {
    "id": "u12",
    "name": "Hasitha Gunasekara",
    "location": "Trincomalee",
    "phone": "0760123456",
    "rating": 4.7,
    "reviewCount": 8,
    "avatar": "HG",
    "isVerified": true,
    "nic": "199345678901",
    "password": "hasitha123",
    "email": "hasitha@email.com"
  },
  {
    "id": "u13",
    "name": "Asanka Rodrigo",
    "location": "Jaffna",
    "phone": "0771235678",
    "rating": 4.5,
    "reviewCount": 5,
    "avatar": "AR",
    "isVerified": false,
    "nic": "",
    "password": "asanka123",
    "email": "asanka@email.com"
  },
  {
    "id": "u14",
    "name": "Upali Wickramasinghe",
    "location": "Kalutara",
    "phone": "0712346789",
    "rating": 4.9,
    "reviewCount": 14,
    "avatar": "UW",
    "isVerified": true,
    "nic": "197723456789",
    "password": "upali123",
    "email": "upali@email.com"
  },
  {
    "id": "u15",
    "name": "Deepa Madusanka",
    "location": "Polonnaruwa",
    "phone": "0763457890",
    "rating": 4.8,
    "reviewCount": 6,
    "avatar": "DM",
    "isVerified": true,
    "nic": "199678901234",
    "password": "deepa123",
    "email": "deepa@email.com"
  }
];

export const INITIAL_TOOLS = [
  {
    "id": "t1",
    "title": "Demolition Jackhammer",
    "category": "Power Tools",
    "ownerId": "u1",
    "description": "2200W electric jackhammer. Concrete breaking and tile removal. Chisels included.",
    "rate": 3500,
    "deposit": 8000,
    "location": "Colombo 05",
    "mapX": 45,
    "mapY": 35,
    "availability": "available",
    "rating": 4.9,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t2",
    "title": "Angle Grinder 9 inch",
    "category": "Power Tools",
    "ownerId": "u4",
    "description": "Heavy duty 2200W angle grinder. Cutting and grinding discs included.",
    "rate": 1500,
    "deposit": 4000,
    "location": "Gampaha",
    "mapX": 40,
    "mapY": 28,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t3",
    "title": "Rotary Hammer Drill",
    "category": "Power Tools",
    "ownerId": "u7",
    "description": "SDS-Plus rotary hammer. Drills concrete and masonry with ease.",
    "rate": 2000,
    "deposit": 5000,
    "location": "Kurunegala",
    "mapX": 25,
    "mapY": 48,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t4",
    "title": "Electric Circular Saw",
    "category": "Power Tools",
    "ownerId": "u10",
    "description": "185mm blade circular saw. Clean straight cuts in wood and plywood.",
    "rate": 1800,
    "deposit": 4500,
    "location": "Ratnapura",
    "mapX": 35,
    "mapY": 70,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t5",
    "title": "Cordless Impact Driver",
    "category": "Power Tools",
    "ownerId": "u14",
    "description": "18V Li-Ion impact driver with 2 batteries. High torque fastening.",
    "rate": 1200,
    "deposit": 3000,
    "location": "Kalutara",
    "mapX": 48,
    "mapY": 72,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t6",
    "title": "Reciprocating Saw",
    "category": "Power Tools",
    "ownerId": "u5",
    "description": "13A reciprocating saw. Demolition and pruning. 5 blades included.",
    "rate": 1600,
    "deposit": 4000,
    "location": "Galle",
    "mapX": 50,
    "mapY": 82,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t7",
    "title": "Jigsaw Electric",
    "category": "Power Tools",
    "ownerId": "u8",
    "description": "Pendulum jigsaw for curved cuts. 10 blade set included.",
    "rate": 1000,
    "deposit": 2500,
    "location": "Negombo",
    "mapX": 38,
    "mapY": 22,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t8",
    "title": "Belt Sander 4 inch",
    "category": "Power Tools",
    "ownerId": "u11",
    "description": "690W belt sander. Smooth wood surfaces fast. Belt rolls included.",
    "rate": 1400,
    "deposit": 3500,
    "location": "Badulla",
    "mapX": 60,
    "mapY": 68,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t9",
    "title": "Random Orbital Sander",
    "category": "Power Tools",
    "ownerId": "u3",
    "description": "Palm sander with dust bag. Ideal for finishing furniture.",
    "rate": 900,
    "deposit": 2000,
    "location": "Maharagama",
    "mapX": 65,
    "mapY": 55,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t10",
    "title": "Bench Grinder 8 inch",
    "category": "Power Tools",
    "ownerId": "u1",
    "description": "Twin wheel bench grinder. Sharpen chisels and drill bits.",
    "rate": 1100,
    "deposit": 3000,
    "location": "Colombo 05",
    "mapX": 45,
    "mapY": 35,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t11",
    "title": "Heat Gun 2000W",
    "category": "Power Tools",
    "ownerId": "u4",
    "description": "Variable temp heat gun. Paint stripping and PVC bending.",
    "rate": 800,
    "deposit": 2000,
    "location": "Gampaha",
    "mapX": 40,
    "mapY": 28,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t12",
    "title": "Router Electric 2HP",
    "category": "Power Tools",
    "ownerId": "u7",
    "description": "2HP plunge router with 10-piece bit set. Perfect for cabinetry.",
    "rate": 1700,
    "deposit": 4000,
    "location": "Kurunegala",
    "mapX": 25,
    "mapY": 48,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t13",
    "title": "Tile Cutter Electric",
    "category": "Power Tools",
    "ownerId": "u5",
    "description": "Wet tile cutter. Diamond blade for ceramic and porcelain tiles.",
    "rate": 2200,
    "deposit": 5500,
    "location": "Galle",
    "mapX": 50,
    "mapY": 82,
    "availability": "available",
    "rating": 4.9,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t14",
    "title": "Wall Chaser Machine",
    "category": "Power Tools",
    "ownerId": "u2",
    "description": "Dual blade wall chaser for electrical cable channels.",
    "rate": 2500,
    "deposit": 6000,
    "location": "Kandy",
    "mapX": 30,
    "mapY": 65,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t15",
    "title": "Heavy Demolition Breaker",
    "category": "Power Tools",
    "ownerId": "u10",
    "description": "10kg electric demolition breaker. Breaks reinforced concrete fast.",
    "rate": 4000,
    "deposit": 9000,
    "location": "Ratnapura",
    "mapX": 35,
    "mapY": 70,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t16",
    "title": "Drywall Screwdriver",
    "category": "Power Tools",
    "ownerId": "u13",
    "description": "Auto feed drywall screwdriver. Install plasterboard quickly.",
    "rate": 700,
    "deposit": 1500,
    "location": "Jaffna",
    "mapX": 18,
    "mapY": 12,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t17",
    "title": "Planer Electric",
    "category": "Power Tools",
    "ownerId": "u8",
    "description": "750W electric planer. 2mm depth, 82mm width. Ideal for doors.",
    "rate": 1300,
    "deposit": 3200,
    "location": "Negombo",
    "mapX": 38,
    "mapY": 22,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t18",
    "title": "Car Orbital Polisher",
    "category": "Power Tools",
    "ownerId": "u15",
    "description": "900W dual action orbital polisher. Restore car paint shine.",
    "rate": 1000,
    "deposit": 2500,
    "location": "Polonnaruwa",
    "mapX": 45,
    "mapY": 48,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t19",
    "title": "Oscillating Multi-Tool",
    "category": "Power Tools",
    "ownerId": "u6",
    "description": "Oscillating multi-tool. Sanding, cutting in tight spaces.",
    "rate": 1100,
    "deposit": 2800,
    "location": "Matara",
    "mapX": 55,
    "mapY": 88,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t20",
    "title": "Air Compressor 50L",
    "category": "Power Tools",
    "ownerId": "u12",
    "description": "50L air compressor 2HP. Powers nail guns and spray guns.",
    "rate": 2800,
    "deposit": 7000,
    "location": "Trincomalee",
    "mapX": 55,
    "mapY": 32,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t21",
    "title": "Concrete Mixer 350L",
    "category": "Heavy Machinery",
    "ownerId": "u1",
    "description": "Electric concrete mixer 350L capacity. Mixes concrete in minutes.",
    "rate": 5000,
    "deposit": 12000,
    "location": "Colombo 05",
    "mapX": 45,
    "mapY": 35,
    "availability": "available",
    "rating": 4.9,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t22",
    "title": "Plate Compactor Petrol",
    "category": "Heavy Machinery",
    "ownerId": "u4",
    "description": "Petrol plate compactor. Compacts soil, gravel and asphalt.",
    "rate": 6000,
    "deposit": 14000,
    "location": "Gampaha",
    "mapX": 40,
    "mapY": 28,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t23",
    "title": "Electric Jackhammer 65lb",
    "category": "Heavy Machinery",
    "ownerId": "u14",
    "description": "65lb demolition hammer. Breaks up driveways and foundations.",
    "rate": 5500,
    "deposit": 13000,
    "location": "Kalutara",
    "mapX": 48,
    "mapY": 72,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t24",
    "title": "Concrete Vibrator",
    "category": "Heavy Machinery",
    "ownerId": "u7",
    "description": "Electric concrete vibrator 35mm head. Removes air bubbles.",
    "rate": 2500,
    "deposit": 6000,
    "location": "Kurunegala",
    "mapX": 25,
    "mapY": 48,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t25",
    "title": "Generator 7kVA Petrol",
    "category": "Heavy Machinery",
    "ownerId": "u5",
    "description": "7kVA portable generator. Powers construction site equipment.",
    "rate": 8000,
    "deposit": 20000,
    "location": "Galle",
    "mapX": 50,
    "mapY": 82,
    "availability": "available",
    "rating": 4.9,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t26",
    "title": "Submersible Water Pump",
    "category": "Heavy Machinery",
    "ownerId": "u2",
    "description": "2 inch submersible pump. Removes flood water fast.",
    "rate": 3000,
    "deposit": 7000,
    "location": "Kandy",
    "mapX": 30,
    "mapY": 65,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t27",
    "title": "Centrifugal Water Pump",
    "category": "Heavy Machinery",
    "ownerId": "u10",
    "description": "3 inch surface pump. Irrigation and construction site use.",
    "rate": 3500,
    "deposit": 8000,
    "location": "Ratnapura",
    "mapX": 35,
    "mapY": 70,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t28",
    "title": "Concrete Road Saw",
    "category": "Heavy Machinery",
    "ownerId": "u3",
    "description": "14 inch diamond blade road cutter. For roads and slabs.",
    "rate": 7000,
    "deposit": 15000,
    "location": "Maharagama",
    "mapX": 65,
    "mapY": 55,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t29",
    "title": "Welding Machine 200A",
    "category": "Heavy Machinery",
    "ownerId": "u8",
    "description": "Arc welder 200A. Welding electrode set and mask included.",
    "rate": 3000,
    "deposit": 7000,
    "location": "Negombo",
    "mapX": 38,
    "mapY": 22,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t30",
    "title": "Mini Cement Mixer 140L",
    "category": "Heavy Machinery",
    "ownerId": "u11",
    "description": "140L portable mini cement mixer. Light enough to carry upstairs.",
    "rate": 2500,
    "deposit": 6000,
    "location": "Badulla",
    "mapX": 60,
    "mapY": 68,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t31",
    "title": "Core Drill Rig",
    "category": "Heavy Machinery",
    "ownerId": "u1",
    "description": "Diamond core drill rig. Drills reinforced concrete walls.",
    "rate": 8000,
    "deposit": 18000,
    "location": "Colombo 05",
    "mapX": 45,
    "mapY": 35,
    "availability": "available",
    "rating": 4.9,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t32",
    "title": "Electric Pallet Jack",
    "category": "Heavy Machinery",
    "ownerId": "u12",
    "description": "Electric pallet jack 2 ton. Move heavy loads in warehouse.",
    "rate": 5000,
    "deposit": 12000,
    "location": "Trincomalee",
    "mapX": 55,
    "mapY": 32,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t33",
    "title": "Portable Scissor Lift",
    "category": "Heavy Machinery",
    "ownerId": "u5",
    "description": "3m portable scissor lift. Safe aerial work at height.",
    "rate": 9000,
    "deposit": 20000,
    "location": "Galle",
    "mapX": 50,
    "mapY": 82,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t34",
    "title": "Block and Tackle Hoist",
    "category": "Heavy Machinery",
    "ownerId": "u6",
    "description": "1 ton chain hoist. Lift heavy machinery and engines.",
    "rate": 2000,
    "deposit": 5000,
    "location": "Matara",
    "mapX": 55,
    "mapY": 88,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t35",
    "title": "Pressure Grouting Machine",
    "category": "Heavy Machinery",
    "ownerId": "u15",
    "description": "Electric grouting pump. Waterproofing and crack injection.",
    "rate": 6000,
    "deposit": 14000,
    "location": "Polonnaruwa",
    "mapX": 45,
    "mapY": 48,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t36",
    "title": "Grass Trimmer Petrol",
    "category": "Gardening",
    "ownerId": "u3",
    "description": "2-stroke petrol grass trimmer. Full fuel tank included.",
    "rate": 1200,
    "deposit": 3000,
    "location": "Maharagama",
    "mapX": 65,
    "mapY": 55,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t37",
    "title": "Lawn Mower Self-Propelled",
    "category": "Gardening",
    "ownerId": "u4",
    "description": "Self-propelled lawn mower 18 inch cut. Grass bag included.",
    "rate": 2000,
    "deposit": 5000,
    "location": "Gampaha",
    "mapX": 40,
    "mapY": 28,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t38",
    "title": "Hedge Trimmer Electric",
    "category": "Gardening",
    "ownerId": "u8",
    "description": "550W hedge trimmer 45cm blade. Neat hedge and shrub cutting.",
    "rate": 1000,
    "deposit": 2500,
    "location": "Negombo",
    "mapX": 38,
    "mapY": 22,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t39",
    "title": "Garden Tiller Cultivator",
    "category": "Gardening",
    "ownerId": "u5",
    "description": "Petrol rotary tiller. Breaks new ground for garden beds.",
    "rate": 3000,
    "deposit": 7000,
    "location": "Galle",
    "mapX": 50,
    "mapY": 82,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t40",
    "title": "Chainsaw 16 inch Petrol",
    "category": "Gardening",
    "ownerId": "u7",
    "description": "Petrol chainsaw 16 inch bar. Tree felling and log cutting.",
    "rate": 3500,
    "deposit": 8000,
    "location": "Kurunegala",
    "mapX": 25,
    "mapY": 48,
    "availability": "available",
    "rating": 4.9,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t41",
    "title": "Leaf Blower Backpack",
    "category": "Gardening",
    "ownerId": "u10",
    "description": "Petrol backpack blower. Clears leaves and debris quickly.",
    "rate": 1400,
    "deposit": 3500,
    "location": "Ratnapura",
    "mapX": 35,
    "mapY": 70,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t42",
    "title": "Garden Water Pump",
    "category": "Gardening",
    "ownerId": "u2",
    "description": "1HP garden water pump. Irrigation and pond circulation.",
    "rate": 1800,
    "deposit": 4000,
    "location": "Kandy",
    "mapX": 30,
    "mapY": 65,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t43",
    "title": "Electric Pruning Shears",
    "category": "Gardening",
    "ownerId": "u13",
    "description": "Li-Ion electric pruning shear. Cuts branches up to 30mm.",
    "rate": 800,
    "deposit": 2000,
    "location": "Jaffna",
    "mapX": 18,
    "mapY": 12,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t44",
    "title": "Soil Aerator Roller",
    "category": "Gardening",
    "ownerId": "u14",
    "description": "Manual lawn aerator roller. Improves grass root growth.",
    "rate": 1500,
    "deposit": 3500,
    "location": "Kalutara",
    "mapX": 48,
    "mapY": 72,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t45",
    "title": "Backpack Sprayer 16L",
    "category": "Gardening",
    "ownerId": "u11",
    "description": "Manual backpack sprayer 16L. Pesticide and fertilizer spray.",
    "rate": 600,
    "deposit": 1500,
    "location": "Badulla",
    "mapX": 60,
    "mapY": 68,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t46",
    "title": "Wood Chipper Electric",
    "category": "Gardening",
    "ownerId": "u15",
    "description": "2500W electric wood chipper. Turns branches into mulch.",
    "rate": 4000,
    "deposit": 9000,
    "location": "Polonnaruwa",
    "mapX": 45,
    "mapY": 48,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t47",
    "title": "Broadcast Seeder Spreader",
    "category": "Gardening",
    "ownerId": "u6",
    "description": "Push broadcast spreader. Seeds and fertilizes lawns evenly.",
    "rate": 700,
    "deposit": 1800,
    "location": "Matara",
    "mapX": 55,
    "mapY": 88,
    "availability": "available",
    "rating": 4.4,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t48",
    "title": "High Pressure Washer 140B",
    "category": "Cleaning",
    "ownerId": "u2",
    "description": "140 Bar pressure washer. Foam bottle and nozzles included.",
    "rate": 1800,
    "deposit": 5000,
    "location": "Kandy",
    "mapX": 30,
    "mapY": 65,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t49",
    "title": "Industrial Wet Dry Vacuum",
    "category": "Cleaning",
    "ownerId": "u4",
    "description": "30L wet and dry vacuum. Construction dust and water pickup.",
    "rate": 1500,
    "deposit": 3500,
    "location": "Gampaha",
    "mapX": 40,
    "mapY": 28,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t50",
    "title": "Steam Cleaner Floor",
    "category": "Cleaning",
    "ownerId": "u8",
    "description": "Floor steam cleaner. Kills bacteria, removes stubborn stains.",
    "rate": 1200,
    "deposit": 3000,
    "location": "Negombo",
    "mapX": 38,
    "mapY": 22,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t51",
    "title": "Carpet Extractor Machine",
    "category": "Cleaning",
    "ownerId": "u3",
    "description": "Carpet deep cleaner. Hot water extraction method.",
    "rate": 2000,
    "deposit": 5000,
    "location": "Maharagama",
    "mapX": 65,
    "mapY": 55,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t52",
    "title": "Pressure Washer 200 Bar",
    "category": "Cleaning",
    "ownerId": "u1",
    "description": "200 Bar pressure washer. Industrial cleaning power.",
    "rate": 2500,
    "deposit": 6000,
    "location": "Colombo 05",
    "mapX": 45,
    "mapY": 35,
    "availability": "available",
    "rating": 4.9,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t53",
    "title": "Floor Scrubber Machine",
    "category": "Cleaning",
    "ownerId": "u7",
    "description": "Walk behind floor scrubber. Tile and concrete cleaning.",
    "rate": 3000,
    "deposit": 7000,
    "location": "Kurunegala",
    "mapX": 25,
    "mapY": 48,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t54",
    "title": "Gutter Cleaning Vacuum Kit",
    "category": "Cleaning",
    "ownerId": "u5",
    "description": "Gutter vac attachment kit for standard wet dry vac.",
    "rate": 500,
    "deposit": 1200,
    "location": "Galle",
    "mapX": 50,
    "mapY": 82,
    "availability": "available",
    "rating": 4.4,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t55",
    "title": "Pool Vacuum Cleaner",
    "category": "Cleaning",
    "ownerId": "u10",
    "description": "Manual pool vacuum head and pole set.",
    "rate": 1000,
    "deposit": 2500,
    "location": "Ratnapura",
    "mapX": 35,
    "mapY": 70,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t56",
    "title": "16-Step Aluminium Ladder",
    "category": "Ladders",
    "ownerId": "u1",
    "description": "Multi-purpose folding ladder. 16 feet extended height.",
    "rate": 1000,
    "deposit": 4000,
    "location": "Colombo 05",
    "mapX": 45,
    "mapY": 35,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t57",
    "title": "Extension Ladder 20ft",
    "category": "Ladders",
    "ownerId": "u4",
    "description": "20 foot aluminium extension ladder. Anti-slip rubber feet.",
    "rate": 1500,
    "deposit": 4500,
    "location": "Gampaha",
    "mapX": 40,
    "mapY": 28,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t58",
    "title": "Scaffold Tower 5m",
    "category": "Ladders",
    "ownerId": "u14",
    "description": "Aluminium scaffold tower 5m. Wide platform with guard rail.",
    "rate": 4000,
    "deposit": 10000,
    "location": "Kalutara",
    "mapX": 48,
    "mapY": 72,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t59",
    "title": "Attic Access Ladder 3m",
    "category": "Ladders",
    "ownerId": "u7",
    "description": "Folding attic ladder 3m. Easy ceiling hatch installation.",
    "rate": 800,
    "deposit": 2000,
    "location": "Kurunegala",
    "mapX": 25,
    "mapY": 48,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t60",
    "title": "Trestle Sawhorse Pair",
    "category": "Ladders",
    "ownerId": "u5",
    "description": "Adjustable sawhorse pair. Holds timber and sheet materials.",
    "rate": 600,
    "deposit": 1500,
    "location": "Galle",
    "mapX": 50,
    "mapY": 82,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t61",
    "title": "Roof Ladder Hook",
    "category": "Ladders",
    "ownerId": "u2",
    "description": "Roof ridge hook ladder. Safe roof access for repairs.",
    "rate": 700,
    "deposit": 1800,
    "location": "Kandy",
    "mapX": 30,
    "mapY": 65,
    "availability": "available",
    "rating": 4.4,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t62",
    "title": "Platform Step Ladder 6ft",
    "category": "Ladders",
    "ownerId": "u8",
    "description": "Wide platform step ladder. Large non-slip work platform.",
    "rate": 900,
    "deposit": 2200,
    "location": "Negombo",
    "mapX": 38,
    "mapY": 22,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t63",
    "title": "Combination Multi Ladder",
    "category": "Ladders",
    "ownerId": "u11",
    "description": "Multi-use combination ladder 4x3. Step, extension and lean modes.",
    "rate": 1300,
    "deposit": 3500,
    "location": "Badulla",
    "mapX": 60,
    "mapY": 68,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t64",
    "title": "Diamond Tile Drilling Set",
    "category": "Hand Tools",
    "ownerId": "u3",
    "description": "10-piece diamond tile drilling set. Fits standard drills.",
    "rate": 400,
    "deposit": 1000,
    "location": "Maharagama",
    "mapX": 65,
    "mapY": 55,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t65",
    "title": "Pipe Wrench Set",
    "category": "Hand Tools",
    "ownerId": "u6",
    "description": "14 inch and 18 inch pipe wrench set. Chrome steel.",
    "rate": 500,
    "deposit": 1200,
    "location": "Matara",
    "mapX": 55,
    "mapY": 88,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t66",
    "title": "Masonry Chisel Set",
    "category": "Hand Tools",
    "ownerId": "u13",
    "description": "8-piece cold and masonry chisel set. Concrete and stone.",
    "rate": 300,
    "deposit": 800,
    "location": "Jaffna",
    "mapX": 18,
    "mapY": 12,
    "availability": "available",
    "rating": 4.4,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t67",
    "title": "Chalk Line and Level Kit",
    "category": "Hand Tools",
    "ownerId": "u15",
    "description": "Chalk line reel and 4 foot spirit level combo.",
    "rate": 350,
    "deposit": 900,
    "location": "Polonnaruwa",
    "mapX": 45,
    "mapY": 48,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t68",
    "title": "Block and Bench Plane Set",
    "category": "Hand Tools",
    "ownerId": "u12",
    "description": "Adjustable block plane and bench plane set.",
    "rate": 400,
    "deposit": 1000,
    "location": "Trincomalee",
    "mapX": 55,
    "mapY": 32,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t69",
    "title": "Punch and Drift Set",
    "category": "Hand Tools",
    "ownerId": "u2",
    "description": "Pin punches and drift set. 12 pieces in roll case.",
    "rate": 250,
    "deposit": 600,
    "location": "Kandy",
    "mapX": 30,
    "mapY": 65,
    "availability": "available",
    "rating": 4.4,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t70",
    "title": "Digital Stud Finder",
    "category": "Hand Tools",
    "ownerId": "u4",
    "description": "Digital stud finder. Locates studs, wires and pipes in walls.",
    "rate": 500,
    "deposit": 1200,
    "location": "Gampaha",
    "mapX": 40,
    "mapY": 28,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t71",
    "title": "Digital Angle Finder",
    "category": "Hand Tools",
    "ownerId": "u1",
    "description": "Digital angle protractor. Accurate to 0.1 degrees.",
    "rate": 400,
    "deposit": 1000,
    "location": "Colombo 05",
    "mapX": 45,
    "mapY": 35,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t72",
    "title": "Hand Saw Set Fine",
    "category": "Hand Tools",
    "ownerId": "u7",
    "description": "3-piece hand saw set. Rip, cross cut and pruning saws.",
    "rate": 300,
    "deposit": 800,
    "location": "Kurunegala",
    "mapX": 25,
    "mapY": 48,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t73",
    "title": "G-Clamp Set 6 piece",
    "category": "Hand Tools",
    "ownerId": "u8",
    "description": "G-clamp and bar clamp set. Wood gluing and metal work.",
    "rate": 350,
    "deposit": 900,
    "location": "Negombo",
    "mapX": 38,
    "mapY": 22,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t74",
    "title": "Cable Pulling Machine",
    "category": "Electrical",
    "ownerId": "u1",
    "description": "Electric cable pulling machine. 500m drum capacity.",
    "rate": 3000,
    "deposit": 7000,
    "location": "Colombo 05",
    "mapX": 45,
    "mapY": 35,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t75",
    "title": "Digital Multimeter Pro",
    "category": "Electrical",
    "ownerId": "u4",
    "description": "True RMS digital multimeter. Current, voltage, resistance.",
    "rate": 600,
    "deposit": 1500,
    "location": "Gampaha",
    "mapX": 40,
    "mapY": 28,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t76",
    "title": "Conduit Bender Electric",
    "category": "Electrical",
    "ownerId": "u7",
    "description": "Electric conduit bender. Bends EMT and rigid conduit.",
    "rate": 2000,
    "deposit": 5000,
    "location": "Kurunegala",
    "mapX": 25,
    "mapY": 48,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t77",
    "title": "Wire Stripper Crimper Set",
    "category": "Electrical",
    "ownerId": "u14",
    "description": "Professional wire stripper and crimp tool set.",
    "rate": 400,
    "deposit": 1000,
    "location": "Kalutara",
    "mapX": 48,
    "mapY": 72,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t78",
    "title": "Circuit Breaker Finder",
    "category": "Electrical",
    "ownerId": "u5",
    "description": "Digital circuit breaker finder. No breaker flipping needed.",
    "rate": 700,
    "deposit": 1800,
    "location": "Galle",
    "mapX": 50,
    "mapY": 82,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t79",
    "title": "Non-Contact Voltage Tester",
    "category": "Electrical",
    "ownerId": "u2",
    "description": "Non-contact AC voltage tester pen. Live wire detection.",
    "rate": 350,
    "deposit": 900,
    "location": "Kandy",
    "mapX": 30,
    "mapY": 65,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t80",
    "title": "Cable Drum Reel 50m",
    "category": "Electrical",
    "ownerId": "u10",
    "description": "50m heavy duty extension reel. 13A socket.",
    "rate": 500,
    "deposit": 1200,
    "location": "Ratnapura",
    "mapX": 35,
    "mapY": 70,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t81",
    "title": "Thermal Imaging Camera",
    "category": "Electrical",
    "ownerId": "u12",
    "description": "Thermal imaging camera. Detects hot spots in panels.",
    "rate": 5000,
    "deposit": 12000,
    "location": "Trincomalee",
    "mapX": 55,
    "mapY": 32,
    "availability": "available",
    "rating": 4.9,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t82",
    "title": "3x360 Green Laser Level",
    "category": "Electrical",
    "ownerId": "u3",
    "description": "360 degree green laser level with tripod. 3-plane.",
    "rate": 2500,
    "deposit": 6000,
    "location": "Maharagama",
    "mapX": 65,
    "mapY": 55,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t83",
    "title": "Fish Tape Wire Puller 30m",
    "category": "Electrical",
    "ownerId": "u6",
    "description": "30m steel fish tape. Pulls wire through conduit and walls.",
    "rate": 600,
    "deposit": 1500,
    "location": "Matara",
    "mapX": 55,
    "mapY": 88,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t84",
    "title": "Electric Pipe Threader",
    "category": "Plumbing",
    "ownerId": "u1",
    "description": "Electric pipe threader. Threads 1/2 to 2 inch steel pipe.",
    "rate": 4000,
    "deposit": 9000,
    "location": "Colombo 05",
    "mapX": 45,
    "mapY": 35,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t85",
    "title": "Motorized Drain Snake",
    "category": "Plumbing",
    "ownerId": "u8",
    "description": "Electric drain auger 15m. Clears blocked drains.",
    "rate": 2000,
    "deposit": 5000,
    "location": "Negombo",
    "mapX": 38,
    "mapY": 22,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t86",
    "title": "Pipe Freezing Kit",
    "category": "Plumbing",
    "ownerId": "u5",
    "description": "Pipe freezing spray kit. Stops flow without shutting off.",
    "rate": 1500,
    "deposit": 3500,
    "location": "Galle",
    "mapX": 50,
    "mapY": 82,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t87",
    "title": "MAPP Gas Plumbing Torch",
    "category": "Plumbing",
    "ownerId": "u4",
    "description": "MAPP gas torch kit. Soldering copper pipes safely.",
    "rate": 800,
    "deposit": 2000,
    "location": "Gampaha",
    "mapX": 40,
    "mapY": 28,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t88",
    "title": "Pressure Test Pump",
    "category": "Plumbing",
    "ownerId": "u7",
    "description": "Hand pressure test pump. Tests pipe pressure to 60 bar.",
    "rate": 1200,
    "deposit": 3000,
    "location": "Kurunegala",
    "mapX": 25,
    "mapY": 48,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t89",
    "title": "Copper PVC Pipe Cutter Set",
    "category": "Plumbing",
    "ownerId": "u13",
    "description": "Copper and PVC pipe cutter set. Clean burr-free cuts.",
    "rate": 400,
    "deposit": 1000,
    "location": "Jaffna",
    "mapX": 18,
    "mapY": 12,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t90",
    "title": "Toilet Closet Auger",
    "category": "Plumbing",
    "ownerId": "u11",
    "description": "Closet auger 900mm. Clears toilet blockages without damage.",
    "rate": 600,
    "deposit": 1500,
    "location": "Badulla",
    "mapX": 60,
    "mapY": 68,
    "availability": "available",
    "rating": 4.4,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t91",
    "title": "Sewer Camera Inspection",
    "category": "Plumbing",
    "ownerId": "u15",
    "description": "30m sewer camera. Live video of underground pipe condition.",
    "rate": 5000,
    "deposit": 12000,
    "location": "Polonnaruwa",
    "mapX": 45,
    "mapY": 48,
    "availability": "available",
    "rating": 4.9,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t92",
    "title": "Hydraulic Pipe Bender",
    "category": "Plumbing",
    "ownerId": "u2",
    "description": "Hydraulic pipe bender. Bends conduit and copper pipe cleanly.",
    "rate": 3000,
    "deposit": 7000,
    "location": "Kandy",
    "mapX": 30,
    "mapY": 65,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t93",
    "title": "Table Saw 10 inch",
    "category": "Woodworking",
    "ownerId": "u14",
    "description": "10 inch table saw. Rip fence and mitre gauge included.",
    "rate": 5000,
    "deposit": 12000,
    "location": "Kalutara",
    "mapX": 48,
    "mapY": 72,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t94",
    "title": "Bandsaw 14 inch",
    "category": "Woodworking",
    "ownerId": "u7",
    "description": "14 inch bandsaw. Resawing and curved cuts in thick timber.",
    "rate": 4000,
    "deposit": 10000,
    "location": "Kurunegala",
    "mapX": 25,
    "mapY": 48,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t95",
    "title": "Scroll Saw Electric",
    "category": "Woodworking",
    "ownerId": "u5",
    "description": "Electric scroll saw. Intricate fretwork and decorative cuts.",
    "rate": 2000,
    "deposit": 5000,
    "location": "Galle",
    "mapX": 50,
    "mapY": 82,
    "availability": "available",
    "rating": 4.6,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t96",
    "title": "Mortising Machine Benchtop",
    "category": "Woodworking",
    "ownerId": "u12",
    "description": "Benchtop mortising machine. Square holes for joinery.",
    "rate": 3000,
    "deposit": 7000,
    "location": "Trincomalee",
    "mapX": 55,
    "mapY": 32,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t97",
    "title": "Wood Lathe 12 inch",
    "category": "Woodworking",
    "ownerId": "u3",
    "description": "Variable speed wood lathe. Bowls, spindles and table legs.",
    "rate": 4500,
    "deposit": 10000,
    "location": "Maharagama",
    "mapX": 65,
    "mapY": 55,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t98",
    "title": "Biscuit Joiner Plate",
    "category": "Woodworking",
    "ownerId": "u8",
    "description": "Plate joiner with biscuit assortment. Strong panel joints.",
    "rate": 1200,
    "deposit": 3000,
    "location": "Negombo",
    "mapX": 38,
    "mapY": 22,
    "availability": "available",
    "rating": 4.5,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t99",
    "title": "Pocket Hole Jig System",
    "category": "Woodworking",
    "ownerId": "u1",
    "description": "Pocket hole jig kit. Fast strong furniture joints.",
    "rate": 800,
    "deposit": 2000,
    "location": "Colombo 05",
    "mapX": 45,
    "mapY": 35,
    "availability": "available",
    "rating": 4.7,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  },
  {
    "id": "t100",
    "title": "Dovetail Jig Router Set",
    "category": "Woodworking",
    "ownerId": "u4",
    "description": "Dovetail jig with router guide. Classic furniture joinery.",
    "rate": 1500,
    "deposit": 3500,
    "location": "Gampaha",
    "mapX": 40,
    "mapY": 28,
    "availability": "available",
    "rating": 4.8,
    "health": {
      "motor": "100% Operational",
      "cable": "Safety Tested",
      "bit": "Cleaned",
      "sanitized": "Verified Disinfected"
    },
    "reviews": []
  }
];

export const CATEGORIES = ["All","Power Tools","Heavy Machinery","Gardening","Cleaning","Ladders","Hand Tools","Electrical","Plumbing","Woodworking"];
